# Generated by Django 5.1.5 on 2025-01-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awareness_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_count', models.IntegerField()),
                ('date', models.DateField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_tracking_sessions', to='awareness_sessions.awarenesssession')),
            ],
        ),
        migrations.CreateModel(
            name='EngagementAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_score', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_engagement_sessions', to='awareness_sessions.awarenesssession')),
            ],
        ),
    ]
