# Generated by Django 5.1.5 on 2025-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('achievement_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
